server:
  # 内网IP
  host: 127.0.0.1
  # 端口号
  port: 8090
  # 是否使用ssl协议
  use_ssl: False
  # ssl协议证书
  ssl_crt: /home/ubutnu/work/dataArea/tf_facenet/server.crt
  # ssl协议秘钥
  ssl_key: /home/ubutnu/work/dataArea/tf_facenet/server.key
  # debug 生产请关闭
  debug: True
  # 秘钥
  secret_key: ai_2018@zhousf.com
  # GPU显存配比
  per_process_gpu_memory_fraction: 0.3
  # 模型文件
  face_model_file: /home/ubutnu/work/dataArea/tf_facenet/train/train_dir/train/20190605-180557/20190605-180557.pb
  # 数据库路径
  database_url: mysql+pymysql://root:@localhost:3306/face?charset=utf8


log:
  api_log_dir: /home/ubutnu/work/dataArea/tf_facenet/log/api/
  error_log_dir: /home/ubutnu/work/dataArea/tf_facenet/log/error/
